define('Widget/Main', [
    'DS/PlatformAPI/PlatformAPI',
    'Modules/WidgetManager',
    'Modules/CityApiV2Manager',
    'Modules/CsvDataManager',
    'Modules/SchemaValidator',
    'Modules/SemanticMappingManager',
    'Modules/MetricsEngine'
], function(PlatformAPI, WidgetManager, CityAPI, CsvData, SchemaValidator, Semantic, Metrics) {
    var CFG = window.DJB_WIDGET_CONFIG || {};
    var state = { data:{}, rows:[], selected:null, log:[], zone:'ALL', from:'2026-05-27', to:'2026-08-26' };
    function $(id){ return document.getElementById(id); }
    function log(msg){ state.log.unshift(new Date().toLocaleTimeString() + ' ' + msg); if(state.log.length>40) state.log.pop(); var el=$('log'); if(el) el.textContent=state.log.join('\n'); }
    function status(text, cls){ var el=$('cityStatus'); if(el){ el.textContent=text; el.className='badge ' + (cls||'warn'); } }
    function num(v){ return Metrics.num(v); }
    function fmt(n, d){ return (isFinite(n)?n:0).toFixed(d===undefined?1:d); }
    function renderShell() {
        widget.setTitle(CFG.title || 'DJB Widget');
        widget.setBody('<div class="djb-root">'
            + '<div class="djb-header"><h1>'+escapeHtml(CFG.title)+'</h1><p>'+escapeHtml(CFG.description)+'</p></div>'
            + '<div class="djb-status"><span id="dataStatus" class="badge warn">Data loading</span><span id="cityStatus" class="badge warn">City API starting</span><span id="schemaStatus" class="badge warn">Schema pending</span></div>'
            + '<div class="toolbar"><div class="field"><label>Zone / DMA</label><select id="zone"><option value="ALL">ALL</option></select></div><div class="field"><label>From</label><input id="from" type="date" value="2026-05-27"></div><div class="field"><label>To</label><input id="to" type="date" value="2026-08-26"></div><div class="field"><label>City action</label><select id="action"><option value="highlight">Highlight selected</option><option value="aoi">Draw AOI polygon</option><option value="line">Draw demo pipeline</option><option value="selected">Get selected city items</option><option value="renderSynthetic">Render synthetic data on City</option><option value="clearSynthetic">Clear synthetic overlays</option></select></div><div class="actions"><button id="refresh" type="button">Refresh</button><button id="pair" type="button" class="secondary">Pair</button><button id="ping" type="button" class="secondary">Ping</button><button id="runAction" type="button">Run</button></div></div>'
            + '<div id="kpis" class="grid"></div><div class="layout"><div class="card"><h2 id="chartTitle">Analysis</h2><div id="chart" class="svgbox"></div></div><div class="card"><h2>Production Integration</h2><p class="note">This widget consumes bundled synthetic CSV data, validates schema/semantic IDs, calculates KPIs, and represents selected records on the 3DEXPERIENCE City environment through City API V2 plus legacy 3DEXPERIENCity fallback calls. Use City action: Render synthetic data on City to draw assets, alert points, pipelines and AOI overlays.</p><div id="quality" class="small"></div></div></div><div class="card"><h2>Records / Exceptions</h2><div id="table" class="tablewrap"></div></div><div class="card"><h2>City API Log</h2><div id="log" class="log">Ready</div></div></div>');
        $('refresh').addEventListener('click', refresh);
        $('pair').addEventListener('click', function(){ CityAPI.autoPair(); CityAPI.pair(); });
        $('ping').addEventListener('click', function(){ CityAPI.ping(); });
        $('runAction').addEventListener('click', runCityAction);
        $('zone').addEventListener('change', function(){ state.zone=this.value; render(); });
        $('from').addEventListener('change', function(){ state.from=this.value; render(); });
        $('to').addEventListener('change', function(){ state.to=this.value; render(); });
    }
    function escapeHtml(s){ return String(s||'').replace(/[&<>"']/g, function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
    function kpi(label, value, sub, cls){ return '<div class="kpi"><div class="label">'+escapeHtml(label)+'</div><div class="value '+(cls||'')+'">'+escapeHtml(value)+'</div><div class="sub">'+escapeHtml(sub||'')+'</div></div>'; }
    function loadData() {
        var files = CFG.files || [];
        $('dataStatus').textContent='Loading CSV'; $('dataStatus').className='badge warn';
        return CsvData.loadMany(files, 'assets/data/').then(function(data){
            state.data=data; if(data['02_semantic_mapping.csv']) Semantic.setRows(data['02_semantic_mapping.csv']);
            var validations = files.map(function(f){ return SchemaValidator.validate(f, data[f]); });
            var bad = validations.filter(function(v){return !v.ok;});
            $('schemaStatus').textContent = bad.length ? ('Schema issues: '+bad.length) : 'Schema OK'; $('schemaStatus').className = bad.length ? 'badge crit' : 'badge ok';
            $('quality').innerHTML = validations.map(function(v){ return '<div>'+(v.ok?'<span class="good">OK</span>':'<span class="err">FAIL</span>')+' '+escapeHtml(v.file)+' - rows '+v.rowCount+(v.missing.length?' - missing '+escapeHtml(v.missing.join(', ')):'')+'</div>'; }).join('');
            $('dataStatus').textContent='Data ready'; $('dataStatus').className='badge ok';
            populateZones(); render(); log('CSV loaded and validated.');
        }).catch(function(e){ $('dataStatus').textContent='CSV load failed'; $('dataStatus').className='badge crit'; log(e.message); });
    }
    function populateZones(){ var all=[]; Object.keys(state.data).forEach(function(f){ all=all.concat(Metrics.zones(state.data[f])); }); var seen={}; var z=all.filter(function(x){ if(seen[x]) return false; seen[x]=true; return true; }).sort(); var html=z.map(function(x){return '<option value="'+escapeHtml(x)+'">'+escapeHtml(x)+'</option>';}).join(''); $('zone').innerHTML=html; $('zone').value=state.zone; }
    function filtered(file){ return Metrics.filter(state.data[file]||[], state.zone, state.from, state.to).map(function(r){ return Semantic.enrich(Object.assign({},r)); }); }
    function render(){
        if(CFG.mode==='network') return renderNetwork();
        if(CFG.mode==='geographic') return renderGeographic();
        if(CFG.mode==='nrw') return renderNRW();
        if(CFG.mode==='leak') return renderLeak();
        if(CFG.mode==='quality') return renderQuality();
        if(CFG.mode==='hydraulic') return renderHydraulic();
        if(CFG.mode==='governance') return renderGovernance();
        if(CFG.mode==='sync') return renderSync();
        renderNetwork();
    }
    function renderNetwork(){ var rows=filtered('04_network_operations_daily_summary.csv'); var alerts=filtered('09_alert_log.csv'); var c=Metrics.statusCounts(alerts); state.rows=alerts.slice(0,200); $('kpis').innerHTML=kpi('Avg pressure',fmt(Metrics.avg(rows,'Avg_Pressure_mH2O'))+' mH2O','Selected period')+kpi('Avg flow',fmt(Metrics.avg(rows,'Avg_Flow_m3_hr'))+' m³/hr','Network summary')+kpi('Critical alerts',String(c.Critical||0),'Alert log','err')+kpi('Missing readings',String(Metrics.sum(rows,'Missing_Readings')),'Data quality'); drawBars({'Normal':c.Normal||0,'Warning':c.Warning||0,'Critical':c.Critical||0}, 'Alert count'); renderTable(state.rows, ['Timestamp','Zone_ID','Asset_ID','Network_Element_ID','Parameter','Value','Alarm_Status','Alert_Message']); }
    function renderGeographic(){ var assets=filtered('01_asset_master.csv'); var alerts=filtered('09_alert_log.csv'); state.rows=alerts.concat(assets).slice(0,250); $('kpis').innerHTML=kpi('Assets',assets.length,'Master records')+kpi('Alerts',alerts.length,'Selected period')+kpi('Pipelines',assets.filter(function(r){return r.Asset_Type==='Pipeline';}).length,'Network assets')+kpi('Sensors',assets.filter(function(r){return (r.Associated_Sensor_ID||'').length;}).length,'Mapped sensors'); drawMapLike(assets, alerts); renderTable(state.rows, ['Zone_ID','Asset_ID','Asset_Type','Network_Element_ID','GIS_Feature_ID','Associated_Sensor_ID','Alarm_Status','Latitude','Longitude']); }
    function renderNRW(){ var rows=filtered('05_nrw_zone_daily.csv'); state.rows=rows.slice().sort(function(a,b){return num(b.NRW_Percentage)-num(a.NRW_Percentage);}).slice(0,200); $('kpis').innerHTML=kpi('Avg NRW',fmt(Metrics.avg(rows,'NRW_Percentage'))+'%','Selected zones')+kpi('NRW volume',fmt(Metrics.sum(rows,'NRW_Volume_m3'),0)+' m³','Period total')+kpi('Max NRW',fmt(Metrics.max(rows,'NRW_Percentage'))+'%','Red flag if >35%','err')+kpi('Reliability',fmt(Metrics.avg(rows,'Data_Reliability_pct'))+'%','Data quality'); drawSeriesByZone(rows,'NRW_Percentage'); renderTable(state.rows, ['Date','Zone_ID','System_Input_m3','Billed_Authorized_Consumption_m3','NRW_Volume_m3','NRW_Percentage','Data_Reliability_pct','Status']); }
    function renderLeak(){ var rows=filtered('06_leak_detection_events.csv'); state.rows=rows.slice().sort(function(a,b){return num(b.Leak_Suspicion_Score)-num(a.Leak_Suspicion_Score);}).slice(0,200); $('kpis').innerHTML=kpi('Leak events',rows.length,'Actual vs expected')+kpi('Max leak score',fmt(Metrics.max(rows,'Leak_Suspicion_Score')),'Critical >80','err')+kpi('Est. loss',fmt(Metrics.sum(rows,'Estimated_Loss_m3_hr'))+' m³/hr','Event sum')+kpi('Critical rows',rows.filter(function(r){return r.Severity==='Critical';}).length,'Inspection priority'); drawBars({'Warning':rows.filter(function(r){return r.Severity==='Warning';}).length,'High':rows.filter(function(r){return r.Severity==='High';}).length,'Critical':rows.filter(function(r){return r.Severity==='Critical';}).length}, 'Leak severity'); renderTable(state.rows, ['Timestamp','Zone_ID','Network_Element_ID','Actual_Value','Expected_Value','Deviation','Leak_Suspicion_Score','Estimated_Loss_m3_hr','Severity','Recommended_Action']); }
    function renderQuality(){ var rows=filtered('07_water_quality_daily_summary.csv'); state.rows=rows.slice().sort(function(a,b){return num(b.Critical_Count)-num(a.Critical_Count);}).slice(0,200); $('kpis').innerHTML=kpi('Quality records',rows.length,'Daily summary')+kpi('Critical violations',String(Metrics.sum(rows,'Critical_Count')),'Threshold breaches','err')+kpi('Warnings',String(Metrics.sum(rows,'Warning_Count')),'Threshold warnings')+kpi('Affected sensors',String(unique(rows.filter(function(r){return num(r.Critical_Count)>0;}).map(function(r){return r.Sensor_ID;})).length),'Critical only'); drawBars({'Normal':rows.filter(function(r){return r.Status==='Normal';}).length,'Warning':rows.filter(function(r){return r.Status==='Warning';}).length,'Critical':rows.filter(function(r){return r.Status==='Critical';}).length}, 'Water quality status'); renderTable(state.rows, ['Date','Sensor_ID','Asset_ID','Zone_ID','Parameter','Avg_Value','Warning_Count','Critical_Count','Status','Latitude','Longitude']); }
    function renderHydraulic(){ var rows=filtered('08_hydraulic_simulation_actual_vs_predicted.csv'); state.rows=rows.slice().sort(function(a,b){return Math.abs(num(b.Deviation))-Math.abs(num(a.Deviation));}).slice(0,200); $('kpis').innerHTML=kpi('Simulation rows',rows.length,'Dymola/FMU synthetic')+kpi('Max deviation',fmt(Metrics.max(rows.map(function(r){return {d:Math.abs(num(r.Deviation))};}),'d')),'Actual vs predicted','err')+kpi('Critical status',rows.filter(function(r){return r.Status==='Critical';}).length,'Deviation review')+kpi('Scenarios',String(unique(rows.map(function(r){return r.Scenario_ID;})).length),'Scenario IDs'); drawBars({'Normal':rows.filter(function(r){return r.Status==='Normal';}).length,'Warning':rows.filter(function(r){return r.Status==='Warning';}).length,'Critical':rows.filter(function(r){return r.Status==='Critical';}).length}, 'Simulation status'); renderTable(state.rows, ['Timestamp','Scenario_ID','Zone_ID','Network_Element_ID','Parameter','Actual_Value','Predicted_Value','Deviation','Status','Recommendation']); }
    function renderGovernance(){ var layers=[['Ortho RGB Byte','Raster RGB Byte','Ready','Base map visible'],['DTM Float32','Single band Float32','Ready','Terrain elevation'],['Buildings','Polygon 2.5D','Ready','Set visibility range + terrain'],['Pipeline network','2D LineString','Ready','Clamp terrain + +2m demo offset'],['Road network','2D LineString','Ready','Solid stroke 8px + full range'],['DMA zones','Polygon','Ready','30% opacity + labels']]; state.rows=layers.map(function(r,i){return {Layer:r[0],Type:r[1],Status:r[2],Recommendation:r[3],gis_feature_id:'DJB_LAYER_'+i};}); $('kpis').innerHTML=kpi('Governed layers',layers.length,'Configured')+kpi('CRS','EPSG:32644','Sonia Vihar referential')+kpi('AOI','25.28 km²','Square bounds')+kpi('Demo mode','Visible','Full-range style'); drawBars({'Ready':layers.length,'Warning':0,'Critical':0}, 'Layer status'); renderTable(state.rows, ['Layer','Type','Status','Recommendation']); }
    function renderSync(){ var map=filtered('02_semantic_mapping.csv'); state.rows=map; var missing=map.filter(function(r){return !r.Sensor_Tag || !r.Asset_ID || !r.Geospatial_Feature_ID || !r.Network_Element_ID || !r.FMU_Variable;}).length; $('kpis').innerHTML=kpi('Mappings',map.length,'Semantic rows')+kpi('Missing critical IDs',missing,'Must be zero',missing?'err':'good')+kpi('Zones',unique(map.map(function(r){return r.Zone_ID;})).length,'DMA coverage')+kpi('FMU variables',unique(map.map(function(r){return r.FMU_Variable;})).length,'Simulation sync'); drawBars({'Mapped':map.length-missing,'Missing':missing}, 'Mapping quality'); renderTable(state.rows, ['Sensor_Tag','Asset_ID','Geospatial_Feature_ID','Network_Element_ID','Dymola_Component','FMU_Variable','Parameter','Zone_ID']); }
    function unique(arr){ var s={}; return arr.filter(function(x){ if(!x || s[x]) return false; s[x]=true; return true; }); }
    function renderTable(rows, cols){ var html='<table><thead><tr>'+cols.map(function(c){return '<th>'+escapeHtml(c)+'</th>';}).join('')+'</tr></thead><tbody>'; rows.forEach(function(r,i){ html+='<tr data-i="'+i+'">'+cols.map(function(c){return '<td>'+escapeHtml(r[c]||'')+'</td>';}).join('')+'</tr>'; }); html+='</tbody></table>'; $('table').innerHTML=html; Array.prototype.forEach.call($('table').querySelectorAll('tr[data-i]'), function(tr){ tr.addEventListener('click',function(){ var i=parseInt(this.getAttribute('data-i'),10); state.selected=rows[i]; Array.prototype.forEach.call($('table').querySelectorAll('tr'), function(x){x.classList.remove('selected');}); this.classList.add('selected'); }); }); }
    function drawBars(obj, label){ $('chartTitle').textContent=label; var keys=Object.keys(obj); var max=Math.max(1, Math.max.apply(null, keys.map(function(k){return obj[k];}))); var w=520,h=220,bar=42,gap=24; var svg='<svg viewBox="0 0 '+w+' '+h+'" role="img"><line x1="44" y1="184" x2="500" y2="184" stroke="#cbd5e1"/>'; keys.forEach(function(k,i){ var val=obj[k]; var bh=(val/max)*140; var x=64+i*(bar+gap); var cls=k==='Critical'||k==='High'||k==='Missing'?'bar-crit':(k==='Warning'?'bar-warn':(k==='Normal'||k==='Ready'||k==='Mapped'?'bar-ok':'bar-blue')); svg+='<rect class="'+cls+'" x="'+x+'" y="'+(184-bh)+'" width="'+bar+'" height="'+bh+'" rx="4"></rect><text x="'+(x+bar/2)+'" y="'+(178-bh)+'" text-anchor="middle" font-size="12" fill="#334155">'+val+'</text><text x="'+(x+bar/2)+'" y="205" text-anchor="middle" font-size="11" fill="#334155">'+escapeHtml(k)+'</text>'; }); svg+='</svg>'; $('chart').innerHTML=svg; }
    function drawSeriesByZone(rows, col){ var agg={}; rows.forEach(function(r){ agg[r.Zone_ID]=(agg[r.Zone_ID]||[]).concat(num(r[col])); }); var obj={}; Object.keys(agg).forEach(function(k){ obj[k]=Math.round(agg[k].reduce(function(a,b){return a+b;},0)/agg[k].length*10)/10; }); drawBars(obj, col + ' by zone'); }
    function drawMapLike(assets, alerts){ var xs=assets.map(function(r){return num(r.Longitude);}), ys=assets.map(function(r){return num(r.Latitude);}); var minx=Math.min.apply(null,xs), maxx=Math.max.apply(null,xs), miny=Math.min.apply(null,ys), maxy=Math.max.apply(null,ys); var w=520,h=220; function sx(x){return 40+(x-minx)/(maxx-minx||1)*440;} function sy(y){return 190-(y-miny)/(maxy-miny||1)*150;} var svg='<svg viewBox="0 0 '+w+' '+h+'"><rect x="30" y="20" width="460" height="175" fill="#eff6ff" stroke="#93c5fd" rx="8"/><text x="40" y="38" font-size="11" fill="#075985">Schematic asset locations / use City highlight for precise model object</text>'; assets.slice(0,80).forEach(function(r){ svg+='<circle cx="'+sx(num(r.Longitude))+'" cy="'+sy(num(r.Latitude))+'" r="4" fill="#0ea5e9"><title>'+escapeHtml(r.Asset_ID)+'</title></circle>'; }); alerts.slice(0,30).forEach(function(r){ svg+='<circle cx="'+sx(num(r.Longitude))+'" cy="'+sy(num(r.Latitude))+'" r="6" fill="#ef4444" opacity=".8"><title>'+escapeHtml(r.Alert_ID||r.Asset_ID)+'</title></circle>'; }); svg+='</svg>'; $('chart').innerHTML=svg; $('chartTitle').textContent='Geographic exception schematic'; }
    function runCityAction(){ var a=$('action').value; if(a==='highlight') { var f=state.selected || state.rows[0]; if(!f) { log('No selected row to highlight.'); return; } CityAPI.highlightFeature(f); }
        else if(a==='aoi') { CityAPI.addDemoPolygon('DJB_AOI_SONIA_VIHAR', [[77.228493,28.696644,2],[77.281486,28.696644,2],[77.281486,28.743358,2],[77.228493,28.743358,2],[77.228493,28.696644,2]], {name:'Sonia Vihar AOI', crs:'EPSG:32644'}); }
        else if(a==='line') { CityAPI.addDemoLine('DJB_DEMO_PIPELINE', [[77.237,28.704,4],[77.246,28.714,4],[77.257,28.725,4],[77.271,28.735,4]], {name:'Demo visible pipeline', pipe_id:'PIPE-DEMO'}); }
        else if(a==='selected') { CityAPI.legacy('GetSelectedItems', {publisher:widget.id}); CityAPI.request('getSelectedItems',{}); }
        else if(a==='renderSynthetic') { CityAPI.renderSyntheticOverlay(state.data, state.zone); log('Synthetic telemetry/asset overlay requested for ' + state.zone); }
        else if(a==='clearSynthetic') { CityAPI.clearGeneratedOverlays(); log('Synthetic overlays cleared.'); }
    }
    function refresh(){ state.zone=$('zone').value; state.from=$('from').value; state.to=$('to').value; loadData(); }
    function onLoad(){ renderShell(); CityAPI.setup(PlatformAPI, status, log); loadData(); }
    return { onLoad:onLoad, onResize:function(){}, onViewChange:function(){}, onEdit:function(){}, onRefresh:refresh, endEdit:function(){} };
});
